<?php if ($adminDisplay) { ?>
	<div>
		<form class="ajax-form" data-name="ebooks_blog_post_remove">
			<input name="submit" class="btn btn-xs btn-primary" type="submit" value="Remove This Post" />
			<input type="hidden" name="id" value="<?php echo $postID; ?>" />
			<input type="hidden" name="submitted" />
			<div class="message" style="display:none;">Reloading in <div class="timer">1</div></div>
		</form>
	</div>
<?php } ?> 
<h1 class="blog-title"><?php echo $ss->get_html('ebookstitle'); ?></h1>

<div class="panel panel-default ebooks-blog-post">
	<div class="panel-body">
		<ul class="share-buttons">
			<!-- Facebook Like -->
			<li>
				<div class="fb-like" data-href="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
			</li>
			<!-- Twitter Tweet -->
			<li>
				<a class="twitter-share-button" href="https://twitter.com/intent/tweet?text=Take%20a%20look%20at%20this!">Tweet</a>
			</li>
			<!-- Google +1 -->
			<li>
				<div class="g-plusone" data-size="medium"></div>
			</li>
		</ul>
		<img src="<?php echo $post->get_img_src(); ?>" />
		<h2><?php echo ucwords($title); ?></h2>
		<?php echo $contents; ?>
	</div>
	<div class="panel-footer comments-section" data-post-id="<?php echo $postID; ?>">
		<!--<h3>Comments</h3>-->
		<div class="list-group comments-list">
			<!-- Generated by JavaScript -->
		</div>
		<form class="form-horizontal">
			<fieldset>
				<legend>Post a Comment</legend>
				<div class="form-group">
					<label class="control-label col-sm-2">Comment</label>
					<div class="col-sm-10">
						<textarea class="form-control" name="comment"></textarea>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-sm-2 sr-only">Submit Comment</label>
					<div class="col-sm-10">
						<input type="submit" class="btn btn-primary" name="submit" value="Comment!" />
					</div>
				</div>
			</fieldset>
		</form>
	</div>
</div>


<div class="col col-xs-4 pull-right home-button-container">
	<div class="inner">
		<a href="<?php echo WEB_PATH; ?>"><div class="btn btn-primary">Back to Home</div></a>
		<a href="<?php echo WEB_PATH.'/ebooks'; ?>"><div class="btn btn-success">Back to Blog</div></a>
	</div>
</div>

<script>
	$(document).ready(function () {
		//setTimeout(function () {
		$('.comments-section').each(function () {
			$(this).instantiate_comment_area(
				"<?php echo WEB_PATH; ?>/?location=comments/get/"+$(this).data('post-id'),
				"<?php echo WEB_PATH; ?>/?location=comments/post/"+$(this).data('post-id')
			);
		});
		//}, 5000);
	});
</script>
